/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  DataSourceConfiguration,
} from './data/DataSource/DataSource';


export namespace Components {

  interface AjonpGrid {
    /**
    * The first name
    */
    'columns': string;
    /**
    * The middle name
    */
    'dataSource': DataSourceConfiguration;
  }
  interface AjonpGridAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'columns'?: string;
    /**
    * The middle name
    */
    'dataSource'?: DataSourceConfiguration;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AjonpGrid': Components.AjonpGrid;
  }

  interface StencilIntrinsicElements {
    'ajonp-grid': Components.AjonpGridAttributes;
  }


  interface HTMLAjonpGridElement extends Components.AjonpGrid, HTMLStencilElement {}
  var HTMLAjonpGridElement: {
    prototype: HTMLAjonpGridElement;
    new (): HTMLAjonpGridElement;
  };

  interface HTMLElementTagNameMap {
    'ajonp-grid': HTMLAjonpGridElement
  }

  interface ElementTagNameMap {
    'ajonp-grid': HTMLAjonpGridElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
